// Auto-generated by gecko_add_shaders — do not edit.
// Shader SPIR-V blobs embedded as byte arrays.
#pragma once

namespace shaders {

alignas(4) inline constexpr unsigned char Vertex2D[] = {
#include "vertex2D.vert.spv.inc"
};
alignas(4) inline constexpr unsigned char FillRectFrag[] = {
#include "fillRect.frag.spv.inc"
};
alignas(4) inline constexpr unsigned char FillCircleFrag[] = {
#include "fillCircle.frag.spv.inc"
};
alignas(4) inline constexpr unsigned char StrokeRectFrag[] = {
#include "strokeRect.frag.spv.inc"
};
alignas(4) inline constexpr unsigned char StrokeCircleFrag[] = {
#include "strokeCircle.frag.spv.inc"
};

}  // namespace shaders
